version: "3"

services:
  hdns-ip-updater:
    build: ./
    environment:
      - MQTT_BROKER
      - MQTT_USERNAME
      - MQTT_PASSWORD      
      - MQTT_TOPIC=${MQTT_BASE_TOPIC}/report
      - HDNS_TOKEN
    volumes:
      - ./config.json:/app/config.json